local app=DoApp.DoApp()
app:doCommand([[Window.SwitchMode?WindowMode=kWriteMode]])
app:doCommand([[Edit.SelectAll]])
app:doCommand([[Filter.TimeSignatures]])
app:doCommand([[Window.SwitchMode?WindowMode=kEngraveMode]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kBarNumberDx&Value=string: "-11/4"]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kBarNumberDy&Value=string: "-9/2"]])
app:doCommand([[Edit.SelectNone]])
app:doCommand([[File.AutoSave]])