local app=DoApp.DoApp()
app:doCommand([[Window.SwitchMode?WindowMode=kWriteMode]])
app:doCommand([[UI.InvokePaletteButton?PaletteIndicatorID=kPlayingTechniquePanel.pta.user.thick_barline&PaletteSectionID=kPlayingTechniquesCommonPanel&PropertyButton=false&SetOldValue=false&Set=true&UseLocalOverride=0]])
app:doCommand([[Window.SwitchMode?WindowMode=kEngraveMode]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kPlayingTechniqueStartDX&Value=string: "-83/32"]])
app:doCommand([[UI.InvokePropertyChangeValue?Type=kPlayingTechniqueStartDY&Value=string: "-273/64"]])
app:doCommand([[File.AutoSave]])